# baseURL = "http://example.org/"
# languageCode = "en-us"
# title = "My New Hugo Site"


baseurl = "https://muuuuuuuuuu.github.io/myproject3"
title = "muuuuuuuuuu blog"
copyright = "Copyright &copy; 2017 - Author Name"
canonifyurls = true
theme = "kiera"
publishDir = "docs"

paginate = 10

summaryLength = 30
enableEmoji = true
pygmentsCodeFences = true

[author]
    name = ""
    github = "muuuuuuuuuu"
    gitlab = ""
    linkedin = ""
    facebook = ""
    twitter = "muuuuuuuuuu7"
    instagram = ""


[params]
    tagline = "プログラミング勉強中のアウトプットブログ"
