# baseURL = "http://example.org/"
# languageCode = "en-us"
# title = "My New Hugo Site"


baseurl = "https://muuuuuuuuuu.github.io/myproject"
title = "muuuuuuuuuu blog"
copyright = "Copyright &copy; 2017 - Author Name"
canonifyurls = true
theme = "kiera"
publishDir = "docs"

paginate = 3

summaryLength = 30
enableEmoji = true
pygmentsCodeFences = true

[author]
    name = ""
    github = "https://github.com/muuuuuuuuuu"
    gitlab = ""
    linkedin = ""
    facebook = ""
    twitter = "https://twitter.com/muuuuuuuuuu7/with_replies"
    instagram = ""
    

[params]
    tagline = "プログラミング勉強中のアウトプットブログ"
